__all__ = ["TokenType"]

class TokenType :
  COMMA, SEMICOLON, \
  \
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, \
  \
  PLUS, MINUS, SLASH, STAR, AMPERSAND, \
  \
  BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, \
  GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, \
  \
  IDENTIFIER, NUM, INT, \
  \
  ELSE, FOR, IF, RETURN, WHILE, \
  \
  EOF =  range(28)


